services:
  projektowaniaoprogramowania:
    container_name: backend
    image: projektowaniaoprogramowania
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "127.0.0.1:5000:80"
  postgres:
    container_name: database
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
networks:
  default:
    name: po_network
    driver: bridge