// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using projektowaniaOprogramowania.Models;

namespace projektowaniaOprogramowania.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20231221132515_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.CollegeStructures.JezykViewModel", b =>
                {
                    b.Property<string>("EnumLiteral")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("EnumLiteral");

                    b.ToTable("jezyki");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.CollegeStructures.KierunekViewModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CzasTrwaniaWSemestrach")
                        .HasColumnType("integer");

                    b.Property<int>("Czesne")
                        .HasColumnType("integer");

                    b.Property<int>("CzesneDlaCudzoziemcow")
                        .HasColumnType("integer");

                    b.Property<string>("Dyscyplina")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("FkIdWydzial")
                        .HasColumnType("bigint");

                    b.Property<string>("Jezyk")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NazwaKierunku")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ProfilKierunku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SkrotKierunku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("StopienStudiow")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TrybStudiowania")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FkIdWydzial");

                    b.ToTable("kierunki");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.CollegeStructures.MiastoViewModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("NazwaMiasta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("miasta");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.CollegeStructures.WydzialViewModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("MiastoId")
                        .HasColumnType("bigint");

                    b.Property<string>("NazwaWydzialu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NumerWydzialu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("MiastoId");

                    b.ToTable("wydzialy");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.DodatkoweOsiagniecieViewModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DataZdobycia")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("FkIdPodanieKandydata")
                        .HasColumnType("bigint");

                    b.Property<long>("FkIdPrzelicznikOsiagniec")
                        .HasColumnType("bigint");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(1000000)
                        .HasColumnType("character varying(1000000)");

                    b.HasKey("Id");

                    b.HasIndex("FkIdPodanieKandydata");

                    b.HasIndex("FkIdPrzelicznikOsiagniec");

                    b.ToTable("dodatkowe_osiagniecia");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.DorobekNaukowyViewModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DataUzyskaniaDorobku")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("FkIdKategoriaDorobku")
                        .HasColumnType("bigint");

                    b.Property<long>("FkIdPodanieNaIIStopien")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FkIdKategoriaDorobku");

                    b.HasIndex("FkIdPodanieNaIIStopien");

                    b.ToTable("dorobei_naukowe");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.KategoriaDorobkuViewModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("NazwaKategoriiDorobku")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("kategorie_dorobku");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.KategoriaOsiagnieciaViewModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("NazwaKategorii")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("kategorie_osiagniecia");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.KierunekNaPodaniuViewModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("FkIdKierunek")
                        .HasColumnType("bigint");

                    b.Property<long>("FkIdPodanieKandydata")
                        .HasColumnType("bigint");

                    b.Property<int>("Priorytet")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FkIdKierunek");

                    b.HasIndex("FkIdPodanieKandydata");

                    b.ToTable("kierunki_na_podaniach");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.MaturaViewModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DataPrzystapieniaDoMatury")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("matury");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.OcenaViewModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("FkIdPrzedmiot")
                        .HasColumnType("bigint");

                    b.Property<long>("Maturaid")
                        .HasColumnType("bigint");

                    b.Property<int>("WartoscProcentowa")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FkIdPrzedmiot");

                    b.HasIndex("Maturaid");

                    b.ToTable("oceny");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PodanieKandydataViewModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("CzyAktywny")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataZlozeniaPodania")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FkIdKandydat")
                        .HasColumnType("character varying(10)");

                    b.Property<long>("FkIdRekrutacja")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FkIdKandydat");

                    b.HasIndex("FkIdRekrutacja");

                    b.ToTable("podanie_kandydata");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PodanieNaIIStopienViewModel", b =>
                {
                    b.Property<long>("PkFkIdPodanieKandydata")
                        .HasColumnType("bigint");

                    b.Property<float>("OcenaZPracyDyplomowej")
                        .HasColumnType("real");

                    b.Property<float>("SredniaZTokuStudiow")
                        .HasColumnType("real");

                    b.HasKey("PkFkIdPodanieKandydata");

                    b.ToTable("podania_na_II_stopien");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PodanieNaIStopienViewModel", b =>
                {
                    b.Property<long>("FkIdPodanieKandydata")
                        .HasColumnType("bigint");

                    b.Property<long>("FkIdMatura")
                        .HasColumnType("bigint");

                    b.HasKey("FkIdPodanieKandydata");

                    b.HasIndex("FkIdMatura");

                    b.ToTable("podania_na_I_stopien");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PracownikDzialuRekrutacjiNaPodanieKandydataViewModel", b =>
                {
                    b.Property<long>("PkFkIdPodanieKandydata")
                        .HasColumnType("bigint");

                    b.Property<string>("PkFkIdPracownikDzialuRekrutacji")
                        .HasColumnType("character varying(10)");

                    b.HasKey("PkFkIdPodanieKandydata", "PkFkIdPracownikDzialuRekrutacji");

                    b.HasIndex("PkFkIdPracownikDzialuRekrutacji");

                    b.ToTable("pracownicy_dzialu_rekrutacji_na_podania_kandydata");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PrzedmiotViewModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("NazwaPrzedmiotu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("przedmioty");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PrzelicznikDorobkuViewModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("FkIdKategoriaDorobku")
                        .HasColumnType("bigint");

                    b.Property<long>("FkIdPrzelicznikKierunkowy")
                        .HasColumnType("bigint");

                    b.Property<int>("PrzyznawanePunkty")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FkIdKategoriaDorobku");

                    b.HasIndex("FkIdPrzelicznikKierunkowy");

                    b.ToTable("przeliczniki_dorobku");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PrzelicznikKierunkowyViewModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("FkIdKierunek")
                        .HasColumnType("bigint");

                    b.Property<int>("MaksymalnaWartoscPrzelicznika")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FkIdKierunek");

                    b.ToTable("przeliczniki_kierunkowe");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PrzelicznikOsiagniecViewModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("FkIdKategoriaOsiagniecia")
                        .HasColumnType("bigint");

                    b.Property<long>("FkIdPrzelicznikKierunkowy")
                        .HasColumnType("bigint");

                    b.Property<int>("PrzyznawanePunkty")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FkIdKategoriaOsiagniecia");

                    b.HasIndex("FkIdPrzelicznikKierunkowy");

                    b.ToTable("przeliczniki_osiagniec");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PrzelicznikPrzedmiotuViewModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("FkIdPrzedmiot")
                        .HasColumnType("bigint");

                    b.Property<long>("FkIdPrzelicznikKierunkowy")
                        .HasColumnType("bigint");

                    b.Property<float>("Wspolczynnik")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("FkIdPrzedmiot");

                    b.HasIndex("FkIdPrzelicznikKierunkowy");

                    b.ToTable("przeliczniki_przedmiotu");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.RekrutacjaViewModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DataOtwarciaRekrutacji")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataZamknieciaPrzyjec")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataZamknieciaRekrutacji")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SemestrRekrutacji")
                        .HasColumnType("integer");

                    b.Property<int>("StatusRekrutacji")
                        .HasColumnType("integer");

                    b.Property<int>("StopienStudiow")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("rekrutacje");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.Users.KandydatViewModel", b =>
                {
                    b.Property<string>("NumerKandydata")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<long>("FkIdOsoba")
                        .HasColumnType("bigint");

                    b.HasKey("NumerKandydata");

                    b.HasIndex("FkIdOsoba");

                    b.ToTable("kandydaci");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.Users.OsobaViewModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("CzyEmailPotwierdzony")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataZarejestrowania")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NumerPaszportu")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Pesel")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.HasKey("Id");

                    b.ToTable("osoby");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.Users.PracownikDzialuRekrutacjiViewModel", b =>
                {
                    b.Property<string>("PkFkIdOsoba")
                        .HasColumnType("character varying(10)");

                    b.Property<long>("FkIdWydzial")
                        .HasColumnType("bigint");

                    b.HasKey("PkFkIdOsoba");

                    b.HasIndex("FkIdWydzial");

                    b.ToTable("pracownik_dzialu_rekrutacji");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.Users.PracownikViewModel", b =>
                {
                    b.Property<string>("NumerPracownika")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("DataZatrudnienia")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("FkIdOsoba")
                        .HasColumnType("bigint");

                    b.Property<string>("TypPracownika")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("NumerPracownika");

                    b.HasIndex("FkIdOsoba");

                    b.ToTable("pracownicy");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.CollegeStructures.KierunekViewModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.CollegeStructures.WydzialViewModel", "Wydzial")
                        .WithMany()
                        .HasForeignKey("FkIdWydzial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wydzial");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.CollegeStructures.WydzialViewModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.CollegeStructures.MiastoViewModel", "Miasto")
                        .WithMany()
                        .HasForeignKey("MiastoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Miasto");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.DodatkoweOsiagniecieViewModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.PodanieKandydataViewModel", "PodanieKandydata")
                        .WithMany()
                        .HasForeignKey("FkIdPodanieKandydata")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projektowaniaOprogramowania.ViewModels.PrzelicznikOsiagniecViewModel", "PrzelicznikOsiagniec")
                        .WithMany()
                        .HasForeignKey("FkIdPrzelicznikOsiagniec")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PodanieKandydata");

                    b.Navigation("PrzelicznikOsiagniec");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.DorobekNaukowyViewModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.KategoriaDorobkuViewModel", "KategoriaDorobku")
                        .WithMany()
                        .HasForeignKey("FkIdKategoriaDorobku")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projektowaniaOprogramowania.ViewModels.PodanieNaIIStopienViewModel", "PodanieNaIIStopien")
                        .WithMany()
                        .HasForeignKey("FkIdPodanieNaIIStopien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KategoriaDorobku");

                    b.Navigation("PodanieNaIIStopien");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.KierunekNaPodaniuViewModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.CollegeStructures.KierunekViewModel", "Kierunek")
                        .WithMany()
                        .HasForeignKey("FkIdKierunek")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projektowaniaOprogramowania.ViewModels.PodanieKandydataViewModel", "PodanieKandydata")
                        .WithMany()
                        .HasForeignKey("FkIdPodanieKandydata")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kierunek");

                    b.Navigation("PodanieKandydata");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.OcenaViewModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.PrzedmiotViewModel", "Przedmiot")
                        .WithMany()
                        .HasForeignKey("FkIdPrzedmiot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projektowaniaOprogramowania.ViewModels.MaturaViewModel", "Matura")
                        .WithMany()
                        .HasForeignKey("Maturaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matura");

                    b.Navigation("Przedmiot");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PodanieKandydataViewModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.Users.KandydatViewModel", "Kandydat")
                        .WithMany()
                        .HasForeignKey("FkIdKandydat");

                    b.HasOne("projektowaniaOprogramowania.ViewModels.RekrutacjaViewModel", "Rekrutacja")
                        .WithMany()
                        .HasForeignKey("FkIdRekrutacja")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kandydat");

                    b.Navigation("Rekrutacja");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PodanieNaIIStopienViewModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.PodanieKandydataViewModel", "PodanieKandydata")
                        .WithMany()
                        .HasForeignKey("PkFkIdPodanieKandydata")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PodanieKandydata");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PodanieNaIStopienViewModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.MaturaViewModel", "Matura")
                        .WithMany()
                        .HasForeignKey("FkIdMatura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projektowaniaOprogramowania.ViewModels.PodanieKandydataViewModel", "PodanieKandydata")
                        .WithMany()
                        .HasForeignKey("FkIdPodanieKandydata")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matura");

                    b.Navigation("PodanieKandydata");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PracownikDzialuRekrutacjiNaPodanieKandydataViewModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.PodanieKandydataViewModel", "PodanieKandydata")
                        .WithMany()
                        .HasForeignKey("PkFkIdPodanieKandydata")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projektowaniaOprogramowania.ViewModels.Users.PracownikDzialuRekrutacjiViewModel", "PracownikDzialuRekrutacji")
                        .WithMany()
                        .HasForeignKey("PkFkIdPracownikDzialuRekrutacji")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PodanieKandydata");

                    b.Navigation("PracownikDzialuRekrutacji");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PrzelicznikDorobkuViewModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.KategoriaDorobkuViewModel", "KategoriaDorobku")
                        .WithMany()
                        .HasForeignKey("FkIdKategoriaDorobku")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projektowaniaOprogramowania.ViewModels.PrzelicznikKierunkowyViewModel", "PrzelicznikKierunkowy")
                        .WithMany()
                        .HasForeignKey("FkIdPrzelicznikKierunkowy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KategoriaDorobku");

                    b.Navigation("PrzelicznikKierunkowy");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PrzelicznikKierunkowyViewModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.CollegeStructures.KierunekViewModel", "Kierunek")
                        .WithMany()
                        .HasForeignKey("FkIdKierunek")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kierunek");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PrzelicznikOsiagniecViewModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.KategoriaOsiagnieciaViewModel", "KategoriaOsiagniecia")
                        .WithMany()
                        .HasForeignKey("FkIdKategoriaOsiagniecia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projektowaniaOprogramowania.ViewModels.PrzelicznikKierunkowyViewModel", "PrzelicznikKierunkowy")
                        .WithMany()
                        .HasForeignKey("FkIdPrzelicznikKierunkowy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KategoriaOsiagniecia");

                    b.Navigation("PrzelicznikKierunkowy");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PrzelicznikPrzedmiotuViewModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.PrzedmiotViewModel", "Przedmiot")
                        .WithMany()
                        .HasForeignKey("FkIdPrzedmiot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projektowaniaOprogramowania.ViewModels.PrzelicznikKierunkowyViewModel", "PrzelicznikKierunkowy")
                        .WithMany()
                        .HasForeignKey("FkIdPrzelicznikKierunkowy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Przedmiot");

                    b.Navigation("PrzelicznikKierunkowy");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.Users.KandydatViewModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.Users.OsobaViewModel", "Osoba")
                        .WithMany()
                        .HasForeignKey("FkIdOsoba")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Osoba");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.Users.PracownikDzialuRekrutacjiViewModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.CollegeStructures.WydzialViewModel", "Wydzial")
                        .WithMany()
                        .HasForeignKey("FkIdWydzial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projektowaniaOprogramowania.ViewModels.Users.PracownikViewModel", "Pracownik")
                        .WithMany()
                        .HasForeignKey("PkFkIdOsoba")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pracownik");

                    b.Navigation("Wydzial");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.Users.PracownikViewModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.Users.OsobaViewModel", "Osoba")
                        .WithMany()
                        .HasForeignKey("FkIdOsoba")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Osoba");
                });
#pragma warning restore 612, 618
        }
    }
}
