// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using projektowaniaOprogramowania.Models;

namespace projektowaniaOprogramowania.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("projektowaniaOprogramowania.Models.Other.PracownikDzialuRekrutacjiNaPodanieKandydataModel", b =>
                {
                    b.Property<long>("PkFkIdPodanieKandydata")
                        .HasColumnType("bigint");

                    b.Property<long>("PkFkIdPracownikDzialuRekrutacji")
                        .HasColumnType("bigint");

                    b.HasKey("PkFkIdPodanieKandydata", "PkFkIdPracownikDzialuRekrutacji");

                    b.HasIndex("PkFkIdPracownikDzialuRekrutacji");

                    b.ToTable("pracownicy_dzialu_rekrutacji_na_podania_kandydata");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.CollegeStructures.KierunekModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CzasTrwaniaWSemestrach")
                        .HasColumnType("integer");

                    b.Property<int>("Czesne")
                        .HasColumnType("integer");

                    b.Property<int>("CzesneDlaCudzoziemcow")
                        .HasColumnType("integer");

                    b.Property<string>("Dyscyplina")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("FkIdPrzelicznik")
                        .HasColumnType("bigint");

                    b.Property<long>("FkIdWydzial")
                        .HasColumnType("bigint");

                    b.Property<int>("Jezyk")
                        .HasMaxLength(20)
                        .HasColumnType("integer");

                    b.Property<string>("NazwaKierunku")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ProfilKierunku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SkrotKierunku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("StopienStudiow")
                        .HasMaxLength(20)
                        .HasColumnType("integer");

                    b.Property<int>("TrybStudiowania")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FkIdPrzelicznik");

                    b.HasIndex("FkIdWydzial");

                    b.ToTable("kierunki");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CzasTrwaniaWSemestrach = 7,
                            Czesne = 0,
                            CzesneDlaCudzoziemcow = 1250,
                            Dyscyplina = "informatyka techniczna i telekomunikacja",
                            FkIdPrzelicznik = 1L,
                            FkIdWydzial = 1L,
                            Jezyk = 0,
                            NazwaKierunku = "Informatyka Stosowana",
                            ProfilKierunku = "ogólnoakademicki",
                            SkrotKierunku = "IST",
                            StopienStudiow = 0,
                            TrybStudiowania = 0
                        },
                        new
                        {
                            Id = 2L,
                            CzasTrwaniaWSemestrach = 7,
                            Czesne = 50,
                            CzesneDlaCudzoziemcow = 1300,
                            Dyscyplina = "informatyka techniczna i telekomunikacja",
                            FkIdPrzelicznik = 2L,
                            FkIdWydzial = 1L,
                            Jezyk = 1,
                            NazwaKierunku = "Informatyka Techniczna w j. angielskim",
                            ProfilKierunku = "ogólnoakademicki",
                            SkrotKierunku = "ITA",
                            StopienStudiow = 1,
                            TrybStudiowania = 0
                        },
                        new
                        {
                            Id = 3L,
                            CzasTrwaniaWSemestrach = 7,
                            Czesne = 0,
                            CzesneDlaCudzoziemcow = 1250,
                            Dyscyplina = "informatyka techniczna i telekomunikacja",
                            FkIdPrzelicznik = 1L,
                            FkIdWydzial = 1L,
                            Jezyk = 0,
                            NazwaKierunku = "Informatyczne Systemy Automatyki",
                            ProfilKierunku = "ogólnoakademicki",
                            SkrotKierunku = "ISA",
                            StopienStudiow = 0,
                            TrybStudiowania = 2
                        },
                        new
                        {
                            Id = 4L,
                            CzasTrwaniaWSemestrach = 7,
                            Czesne = 100,
                            CzesneDlaCudzoziemcow = 1350,
                            Dyscyplina = "informatyka techniczna i telekomunikacja",
                            FkIdPrzelicznik = 2L,
                            FkIdWydzial = 1L,
                            Jezyk = 1,
                            NazwaKierunku = "Informatyka Stosowana w j.angielskim",
                            ProfilKierunku = "",
                            SkrotKierunku = "ISTA",
                            StopienStudiow = 0,
                            TrybStudiowania = 1
                        });
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.CollegeStructures.MiastoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("NazwaMiasta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("miasta");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            NazwaMiasta = "Wrocław"
                        });
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.CollegeStructures.WydzialModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("MiastoId")
                        .HasColumnType("bigint");

                    b.Property<string>("NazwaWydzialu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NumerWydzialu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("MiastoId");

                    b.ToTable("wydzialy");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            MiastoId = 1L,
                            NazwaWydzialu = "Wydział Informatyki i Telekomunikacji",
                            NumerWydzialu = "W04n"
                        });
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.DodatkoweOsiagniecieModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DataZdobycia")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("FkIdPodanieKandydata")
                        .HasColumnType("bigint");

                    b.Property<long>("FkIdPrzelicznikOsiagniec")
                        .HasColumnType("bigint");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(1000000)
                        .HasColumnType("character varying(1000000)");

                    b.HasKey("Id");

                    b.HasIndex("FkIdPodanieKandydata");

                    b.HasIndex("FkIdPrzelicznikOsiagniec");

                    b.ToTable("dodatkowe_osiagniecia");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.DorobekNaukowyModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DataUzyskaniaDorobku")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("FkIdKategoriaDorobku")
                        .HasColumnType("bigint");

                    b.Property<long>("FkIdPodanieNaIIStopien")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FkIdKategoriaDorobku");

                    b.HasIndex("FkIdPodanieNaIIStopien");

                    b.ToTable("dorobei_naukowe");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.KategoriaDorobkuModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("NazwaKategoriiDorobku")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("kategorie_dorobku");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            NazwaKategoriiDorobku = "Publikacja w czasopiśmie"
                        },
                        new
                        {
                            Id = 2L,
                            NazwaKategoriiDorobku = "Publikacja książki"
                        },
                        new
                        {
                            Id = 3L,
                            NazwaKategoriiDorobku = "Publikacja patentu"
                        },
                        new
                        {
                            Id = 4L,
                            NazwaKategoriiDorobku = "Rysunek architektoniczny"
                        });
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.KategoriaOsiagnieciaModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("NazwaKategorii")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("kategorie_osiagniecia");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            NazwaKategorii = "Laureat konkursu - przedmiot ścisły"
                        },
                        new
                        {
                            Id = 2L,
                            NazwaKategorii = "Laureat konkursu - przedmiot humanistyczny"
                        },
                        new
                        {
                            Id = 3L,
                            NazwaKategorii = "Paszport Polsatu"
                        },
                        new
                        {
                            Id = 4L,
                            NazwaKategorii = "Nagroda Nobla"
                        });
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.KierunekNaPodaniuModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("FkIdKierunek")
                        .HasColumnType("bigint");

                    b.Property<long>("FkIdPodanieKandydata")
                        .HasColumnType("bigint");

                    b.Property<int>("Priorytet")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FkIdKierunek");

                    b.HasIndex("FkIdPodanieKandydata");

                    b.ToTable("kierunki_na_podaniach");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.MaturaModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DataPrzystapieniaDoMatury")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("FkIdPodanieNaIStopien")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FkIdPodanieNaIStopien");

                    b.ToTable("matury");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.OcenaModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("FkIdPrzedmiot")
                        .HasColumnType("bigint");

                    b.Property<long>("MaturaId")
                        .HasColumnType("bigint");

                    b.Property<int>("WartoscProcentowa")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FkIdPrzedmiot");

                    b.HasIndex("MaturaId");

                    b.ToTable("oceny");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PodanieKandydataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("CzyAktywny")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataZlozeniaPodania")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("FkIdKandydat")
                        .HasColumnType("bigint");

                    b.Property<long>("FkIdRekrutacja")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FkIdKandydat");

                    b.HasIndex("FkIdRekrutacja");

                    b.ToTable("podania_kandydatow");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CzyAktywny = true,
                            DataZlozeniaPodania = new DateTime(2024, 1, 13, 18, 34, 32, 677, DateTimeKind.Local).AddTicks(1653),
                            FkIdKandydat = 1L,
                            FkIdRekrutacja = 1L
                        });
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PrzedmiotModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("NazwaPrzedmiotu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("przedmioty");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            NazwaPrzedmiotu = "Matematyka podstawowa"
                        },
                        new
                        {
                            Id = 2L,
                            NazwaPrzedmiotu = "Fizyka podstawowa"
                        },
                        new
                        {
                            Id = 3L,
                            NazwaPrzedmiotu = "Chemia podstawowa"
                        },
                        new
                        {
                            Id = 4L,
                            NazwaPrzedmiotu = "Informatyka podstawowa"
                        },
                        new
                        {
                            Id = 5L,
                            NazwaPrzedmiotu = "Geografia podstawowa"
                        },
                        new
                        {
                            Id = 6L,
                            NazwaPrzedmiotu = "Biologia podstawowa"
                        },
                        new
                        {
                            Id = 7L,
                            NazwaPrzedmiotu = "Język polski podstawowy"
                        },
                        new
                        {
                            Id = 8L,
                            NazwaPrzedmiotu = "Język obcy podstawowy"
                        },
                        new
                        {
                            Id = 9L,
                            NazwaPrzedmiotu = "Matematyka rozszerzona"
                        },
                        new
                        {
                            Id = 10L,
                            NazwaPrzedmiotu = "Fizyka rozszerzona"
                        },
                        new
                        {
                            Id = 11L,
                            NazwaPrzedmiotu = "Chemia rozszerzona"
                        },
                        new
                        {
                            Id = 12L,
                            NazwaPrzedmiotu = "Informatyka rozszerzona"
                        },
                        new
                        {
                            Id = 13L,
                            NazwaPrzedmiotu = "Geografia rozszerzona"
                        },
                        new
                        {
                            Id = 14L,
                            NazwaPrzedmiotu = "Biologia rozszerzona"
                        },
                        new
                        {
                            Id = 15L,
                            NazwaPrzedmiotu = "Język polski rozszerzony"
                        },
                        new
                        {
                            Id = 16L,
                            NazwaPrzedmiotu = "Język obcy rozszerzony"
                        });
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PrzelicznikDorobkuModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("FkIdKategoriaDorobku")
                        .HasColumnType("bigint");

                    b.Property<long>("FkIdPrzelicznikKierunkowy")
                        .HasColumnType("bigint");

                    b.Property<int>("PrzyznawanePunkty")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FkIdKategoriaDorobku");

                    b.HasIndex("FkIdPrzelicznikKierunkowy");

                    b.ToTable("przeliczniki_dorobku");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PrzelicznikKierunkowyModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("MaksymalnaWartoscPrzelicznika")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("przeliczniki_kierunkowe");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            MaksymalnaWartoscPrzelicznika = 1
                        },
                        new
                        {
                            Id = 2L,
                            MaksymalnaWartoscPrzelicznika = 1
                        });
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PrzelicznikOsiagniecModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("FkIdKategoriaOsiagniecia")
                        .HasColumnType("bigint");

                    b.Property<long>("FkIdPrzelicznikKierunkowy")
                        .HasColumnType("bigint");

                    b.Property<int>("PrzyznawanePunkty")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FkIdKategoriaOsiagniecia");

                    b.HasIndex("FkIdPrzelicznikKierunkowy");

                    b.ToTable("przeliczniki_osiagniec");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FkIdKategoriaOsiagniecia = 1L,
                            FkIdPrzelicznikKierunkowy = 1L,
                            PrzyznawanePunkty = 0
                        },
                        new
                        {
                            Id = 2L,
                            FkIdKategoriaOsiagniecia = 2L,
                            FkIdPrzelicznikKierunkowy = 2L,
                            PrzyznawanePunkty = 0
                        },
                        new
                        {
                            Id = 3L,
                            FkIdKategoriaOsiagniecia = 3L,
                            FkIdPrzelicznikKierunkowy = 1L,
                            PrzyznawanePunkty = 0
                        },
                        new
                        {
                            Id = 4L,
                            FkIdKategoriaOsiagniecia = 4L,
                            FkIdPrzelicznikKierunkowy = 2L,
                            PrzyznawanePunkty = 0
                        });
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PrzelicznikPrzedmiotuModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("FkIdPrzedmiot")
                        .HasColumnType("bigint");

                    b.Property<long>("FkIdPrzelicznikKierunkowy")
                        .HasColumnType("bigint");

                    b.Property<float>("Wspolczynnik")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("FkIdPrzedmiot");

                    b.HasIndex("FkIdPrzelicznikKierunkowy");

                    b.ToTable("przeliczniki_przedmiotu");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FkIdPrzedmiot = 1L,
                            FkIdPrzelicznikKierunkowy = 1L,
                            Wspolczynnik = 0.2f
                        },
                        new
                        {
                            Id = 2L,
                            FkIdPrzedmiot = 2L,
                            FkIdPrzelicznikKierunkowy = 1L,
                            Wspolczynnik = 0.5f
                        },
                        new
                        {
                            Id = 3L,
                            FkIdPrzedmiot = 3L,
                            FkIdPrzelicznikKierunkowy = 1L,
                            Wspolczynnik = 0.7f
                        });
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.RekrutacjaModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DataOtwarciaRekrutacji")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataZamknieciaPrzyjec")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataZamknieciaRekrutacji")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SemestrRekrutacji")
                        .HasColumnType("integer");

                    b.Property<int>("StatusRekrutacji")
                        .HasColumnType("integer");

                    b.Property<int>("StopienStudiow")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("rekrutacje");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DataOtwarciaRekrutacji = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataZamknieciaPrzyjec = new DateTime(2024, 6, 13, 18, 34, 32, 675, DateTimeKind.Local).AddTicks(597),
                            DataZamknieciaRekrutacji = new DateTime(2024, 6, 13, 18, 34, 32, 676, DateTimeKind.Local).AddTicks(4604),
                            SemestrRekrutacji = 1,
                            StatusRekrutacji = 0,
                            StopienStudiow = 0
                        });
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.Users.OsobaModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("CzyEmailPotwierdzony")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataZarejestrowania")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NumerPaszportu")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Pesel")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.HasKey("Id");

                    b.ToTable("osoby");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PodanieNaStudiaIIStopniaModel", b =>
                {
                    b.HasBaseType("projektowaniaOprogramowania.ViewModels.PodanieKandydataModel");

                    b.Property<float>("OcenaZPracyDyplomowej")
                        .HasColumnType("real");

                    b.Property<float>("SredniaZTokuStudiow")
                        .HasColumnType("real");

                    b.ToTable("podania_na_II_stopien");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PodanieNaStudiaIStopniaModel", b =>
                {
                    b.HasBaseType("projektowaniaOprogramowania.ViewModels.PodanieKandydataModel");

                    b.ToTable("podania_na_I_stopien");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.Users.KandydatModel", b =>
                {
                    b.HasBaseType("projektowaniaOprogramowania.ViewModels.Users.OsobaModel");

                    b.Property<string>("NumerKandydata")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasIndex("NumerKandydata")
                        .IsUnique();

                    b.ToTable("kandydaci");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CzyEmailPotwierdzony = true,
                            DataZarejestrowania = new DateTime(2024, 1, 13, 18, 34, 32, 676, DateTimeKind.Local).AddTicks(6090),
                            Email = "testowykandydat@gmail.com",
                            Haslo = "zahaszowaneHaselko",
                            Imie = "Jan",
                            Login = "testowyKandydat",
                            Nazwisko = "Testowy",
                            Pesel = "59070575419",
                            NumerKandydata = "5907057541"
                        });
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.Users.PracownikModel", b =>
                {
                    b.HasBaseType("projektowaniaOprogramowania.ViewModels.Users.OsobaModel");

                    b.Property<DateTime>("DataZatrudnienia")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NumerPracownika")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TypPracownika")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasIndex("NumerPracownika")
                        .IsUnique();

                    b.ToTable("pracownicy");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.Users.PracownikDzialuRekrutacjiModel", b =>
                {
                    b.HasBaseType("projektowaniaOprogramowania.ViewModels.Users.PracownikModel");

                    b.Property<long>("FkIdWydzial")
                        .HasColumnType("bigint");

                    b.HasIndex("FkIdWydzial");

                    b.ToTable("pracownicy_dzialu_rekrutacji");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.Models.Other.PracownikDzialuRekrutacjiNaPodanieKandydataModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.PodanieKandydataModel", "PodanieKandydata")
                        .WithMany()
                        .HasForeignKey("PkFkIdPodanieKandydata")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projektowaniaOprogramowania.ViewModels.Users.PracownikDzialuRekrutacjiModel", "PracownikDzialuRekrutacji")
                        .WithMany()
                        .HasForeignKey("PkFkIdPracownikDzialuRekrutacji")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PodanieKandydata");

                    b.Navigation("PracownikDzialuRekrutacji");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.CollegeStructures.KierunekModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.PrzelicznikKierunkowyModel", "Przelicznik")
                        .WithMany()
                        .HasForeignKey("FkIdPrzelicznik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projektowaniaOprogramowania.ViewModels.CollegeStructures.WydzialModel", "Wydzial")
                        .WithMany()
                        .HasForeignKey("FkIdWydzial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Przelicznik");

                    b.Navigation("Wydzial");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.CollegeStructures.WydzialModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.CollegeStructures.MiastoModel", "Miasto")
                        .WithMany()
                        .HasForeignKey("MiastoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Miasto");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.DodatkoweOsiagniecieModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.PodanieKandydataModel", "PodanieKandydata")
                        .WithMany()
                        .HasForeignKey("FkIdPodanieKandydata")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projektowaniaOprogramowania.ViewModels.PrzelicznikOsiagniecModel", "PrzelicznikOsiagniec")
                        .WithMany()
                        .HasForeignKey("FkIdPrzelicznikOsiagniec")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PodanieKandydata");

                    b.Navigation("PrzelicznikOsiagniec");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.DorobekNaukowyModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.KategoriaDorobkuModel", "KategoriaDorobku")
                        .WithMany()
                        .HasForeignKey("FkIdKategoriaDorobku")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projektowaniaOprogramowania.ViewModels.PodanieNaStudiaIIStopniaModel", "PodanieNaIIStopien")
                        .WithMany()
                        .HasForeignKey("FkIdPodanieNaIIStopien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KategoriaDorobku");

                    b.Navigation("PodanieNaIIStopien");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.KierunekNaPodaniuModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.CollegeStructures.KierunekModel", "Kierunek")
                        .WithMany()
                        .HasForeignKey("FkIdKierunek")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projektowaniaOprogramowania.ViewModels.PodanieKandydataModel", "PodanieKandydata")
                        .WithMany()
                        .HasForeignKey("FkIdPodanieKandydata")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kierunek");

                    b.Navigation("PodanieKandydata");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.MaturaModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.PodanieNaStudiaIStopniaModel", "PodanieNaIStopien")
                        .WithMany()
                        .HasForeignKey("FkIdPodanieNaIStopien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PodanieNaIStopien");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.OcenaModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.PrzedmiotModel", "Przedmiot")
                        .WithMany()
                        .HasForeignKey("FkIdPrzedmiot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projektowaniaOprogramowania.ViewModels.MaturaModel", "Matura")
                        .WithMany()
                        .HasForeignKey("MaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matura");

                    b.Navigation("Przedmiot");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PodanieKandydataModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.Users.KandydatModel", "Kandydat")
                        .WithMany()
                        .HasForeignKey("FkIdKandydat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projektowaniaOprogramowania.ViewModels.RekrutacjaModel", "Rekrutacja")
                        .WithMany()
                        .HasForeignKey("FkIdRekrutacja")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kandydat");

                    b.Navigation("Rekrutacja");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PrzelicznikDorobkuModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.KategoriaDorobkuModel", "KategoriaDorobku")
                        .WithMany()
                        .HasForeignKey("FkIdKategoriaDorobku")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projektowaniaOprogramowania.ViewModels.PrzelicznikKierunkowyModel", "PrzelicznikKierunkowy")
                        .WithMany("PrzelicznikDorobku")
                        .HasForeignKey("FkIdPrzelicznikKierunkowy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KategoriaDorobku");

                    b.Navigation("PrzelicznikKierunkowy");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PrzelicznikOsiagniecModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.KategoriaOsiagnieciaModel", "KategoriaOsiagniecia")
                        .WithMany()
                        .HasForeignKey("FkIdKategoriaOsiagniecia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projektowaniaOprogramowania.ViewModels.PrzelicznikKierunkowyModel", "PrzelicznikKierunkowy")
                        .WithMany()
                        .HasForeignKey("FkIdPrzelicznikKierunkowy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KategoriaOsiagniecia");

                    b.Navigation("PrzelicznikKierunkowy");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PrzelicznikPrzedmiotuModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.PrzedmiotModel", "Przedmiot")
                        .WithMany()
                        .HasForeignKey("FkIdPrzedmiot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projektowaniaOprogramowania.ViewModels.PrzelicznikKierunkowyModel", "PrzelicznikKierunkowy")
                        .WithMany("PrzelicznikPrzemiotu")
                        .HasForeignKey("FkIdPrzelicznikKierunkowy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Przedmiot");

                    b.Navigation("PrzelicznikKierunkowy");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PodanieNaStudiaIIStopniaModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.PodanieKandydataModel", null)
                        .WithOne()
                        .HasForeignKey("projektowaniaOprogramowania.ViewModels.PodanieNaStudiaIIStopniaModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PodanieNaStudiaIStopniaModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.PodanieKandydataModel", null)
                        .WithOne()
                        .HasForeignKey("projektowaniaOprogramowania.ViewModels.PodanieNaStudiaIStopniaModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.Users.KandydatModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.Users.OsobaModel", null)
                        .WithOne()
                        .HasForeignKey("projektowaniaOprogramowania.ViewModels.Users.KandydatModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.Users.PracownikModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.Users.OsobaModel", null)
                        .WithOne()
                        .HasForeignKey("projektowaniaOprogramowania.ViewModels.Users.PracownikModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.Users.PracownikDzialuRekrutacjiModel", b =>
                {
                    b.HasOne("projektowaniaOprogramowania.ViewModels.CollegeStructures.WydzialModel", "Wydzial")
                        .WithMany()
                        .HasForeignKey("FkIdWydzial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projektowaniaOprogramowania.ViewModels.Users.PracownikModel", null)
                        .WithOne()
                        .HasForeignKey("projektowaniaOprogramowania.ViewModels.Users.PracownikDzialuRekrutacjiModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wydzial");
                });

            modelBuilder.Entity("projektowaniaOprogramowania.ViewModels.PrzelicznikKierunkowyModel", b =>
                {
                    b.Navigation("PrzelicznikDorobku");

                    b.Navigation("PrzelicznikPrzemiotu");
                });
#pragma warning restore 612, 618
        }
    }
}
